// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoldadosDoImperador.Data;

#nullable disable

namespace SoldadosDoImperador.Migrations
{
    [DbContext(typeof(ContextoWarhammer))]
    [Migration("20251016014004_ModificandoModels")]
    partial class ModificandoModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoldadosDoImperador.Models.ItemBatalha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("ItensBatalha");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrazoFinal")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("Ordens");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Soldado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patente")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.ToTable("Soldados");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Treinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuracaoHoras")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("Treinamentos");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.ItemBatalha", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("ItensDeBatalha")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Missao", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("Missoes")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Ordem", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("OrdensRecebidas")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Treinamento", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("Treinamentos")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Soldado", b =>
                {
                    b.Navigation("ItensDeBatalha");

                    b.Navigation("Missoes");

                    b.Navigation("OrdensRecebidas");

                    b.Navigation("Treinamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
