// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoldadosDoImperador.Data;

#nullable disable

namespace SoldadosDoImperador.Migrations
{
    [DbContext(typeof(ContextoWarhammer))]
    [Migration("20251024181141_Refatoracao_Missao_MN")]
    partial class Refatoracao_Missao_MN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoldadosDoImperador.Models.ItemBatalha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especificacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("ItensBatalha");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.MissaoParticipante", b =>
                {
                    b.Property<int>("MissaoId")
                        .HasColumnType("int");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.HasKey("MissaoId", "SoldadoId");

                    b.HasIndex("SoldadoId");

                    b.ToTable("MissoesParticipantes");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PrazoFinal")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("Ordens");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Soldado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("Capitulo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Patente")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.ToTable("Soldados");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Treinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuracaoHoras")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SoldadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoldadoId");

                    b.ToTable("Treinamentos");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.ItemBatalha", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("ItensDeBatalha")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.MissaoParticipante", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Missao", "Missao")
                        .WithMany("Participantes")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("MissoesParticipadas")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Missao");

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Ordem", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("OrdensRecebidas")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Treinamento", b =>
                {
                    b.HasOne("SoldadosDoImperador.Models.Soldado", "Soldado")
                        .WithMany("Treinamentos")
                        .HasForeignKey("SoldadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldado");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Missao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SoldadosDoImperador.Models.Soldado", b =>
                {
                    b.Navigation("ItensDeBatalha");

                    b.Navigation("MissoesParticipadas");

                    b.Navigation("OrdensRecebidas");

                    b.Navigation("Treinamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
